// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfa-Ky86HW_PMvuTB-nq0yx6M65XNXKYY',
    appId: '1:771314863453:web:b4493fe587c26d4f22acb4',
    messagingSenderId: '771314863453',
    projectId: 'gradproject-42f0c',
    authDomain: 'gradproject-42f0c.firebaseapp.com',
    storageBucket: 'gradproject-42f0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpzLuRr2FZMMAn86xdVbRbpAmI5BwRtps',
    appId: '1:771314863453:android:48d16706b01cd55722acb4',
    messagingSenderId: '771314863453',
    projectId: 'gradproject-42f0c',
    storageBucket: 'gradproject-42f0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxzf_sHfjGezp-eH8WN5YEcHLk993IF8',
    appId: '1:771314863453:ios:199c2ae766e7089f22acb4',
    messagingSenderId: '771314863453',
    projectId: 'gradproject-42f0c',
    storageBucket: 'gradproject-42f0c.appspot.com',
    iosBundleId: 'com.example.applicationPart1Test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTxzf_sHfjGezp-eH8WN5YEcHLk993IF8',
    appId: '1:771314863453:ios:199c2ae766e7089f22acb4',
    messagingSenderId: '771314863453',
    projectId: 'gradproject-42f0c',
    storageBucket: 'gradproject-42f0c.appspot.com',
    iosBundleId: 'com.example.applicationPart1Test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfa-Ky86HW_PMvuTB-nq0yx6M65XNXKYY',
    appId: '1:771314863453:web:60cc1dc277b3090922acb4',
    messagingSenderId: '771314863453',
    projectId: 'gradproject-42f0c',
    authDomain: 'gradproject-42f0c.firebaseapp.com',
    storageBucket: 'gradproject-42f0c.appspot.com',
  );
}
